module.exports = [
	{id:"aintnobody", name:"Ain't Nobody"},
	{id:"airhorn", name:"Air Horn"},
	{id:"assbag", name:"Assbag"},
	{id:"badumtss", name:"Ba Dum Tss"},
	{id:"boomheadshot", name:"Boom Headshot"},
	{id:"canttouchthis", name:"Can't Touch This"},
	{id:"combobreaker", name:"C-C-Combo Breaker"},
	{id:"denied", name:"Denied"},
	{id:"doh", name:"DOH!"},
	{id:"doublerainbow", name:"Double Rainbow"},
	{id:"drama", name:"Drama"},
	{id:"dramatic", name:"Dramatic"},
	{id:"dropthebass", name:"Drop The Bass"},
	{id:"fart", name:"Fart"},
	{id:"fatality", name:"Fatality"},
	{id:"fucker", name:"Fucker"},
	{id:"gay", name:"Gay"},
	{id:"gayvictory", name:"Gay Victory"},
	{id:"goat", name:"Goat!"},
	{id:"headshot", name:"Headshot"},
	{id:"hellno", name:"Hell No!"},
	{id:"inception", name:"Inception"},
	{id:"itsatrap", name:"It's a trap!"},
	{id:"jeopardy", name:"Jeopardy"},
	{id:"johncena", name:"John Cena"},
	{id:"leroyjenkins", name:"Leroy Jenkins"},
	{id:"merovingian", name:"Merovingian"},
	{id:"metalgear", name:"Metal Gear"},
	{id:"monsterkill1", name:"Monster Kill 1"},
	{id:"monsterkill2", name:"Monster Kill 2"},
	{id:"nelson", name:"Nelson"},
	{id:"nigger", name:"Nigger nigger nigger nigger"},
	{id:"nooo", name:"Nooooooo!"},
	{id:"ohmy", name:"Oh My!"},
	{id:"ohyeah", name:"Oh Yeah!"},
	{id:"ooh", name:"OOOOOOOH!!!!!"},
	{id:"patenaude", name:"Patenaude"},
	{id:"poi", name:"Poi"},
	{id:"sadtrombone", name:"Sad Trombone"},
	{id:"sexysax", name:"Sexy Sax"},
	{id:"shutup", name:"Shut Up!"},
	{id:"silence", name:"Silence!"},
	{id:"surprisemotherfucker", name:"Surprise Montherfucker!"},
	{id:"thatwaseasy", name:"That Was Easy"},
	{id:"trololo1", name:"Trololo 1"},
	{id:"trololo2", name:"Trololo 2"},
	{id:"turndownforwhat", name:"Turn Down For What!"},
	{id:"ursofucked", name:"U R SO FUCKED"},
	{id:"vuvuzela", name:"Vuvuzela"},
	{id:"wololo", name:"Wololo"},
	{id:"wtfboom", name:"WTF BOOM!"},
	{id:"xfiles", name:"X-Files"},
	{id:"yaunordiquiacrache", name:"Y a un ordi qui a craché!"},
	{id:"youshallnotpass", name:"YOU SHALL NOT PASS!"},
	{id:"youspinme", name:"You Spin Me!"},
	{id:"zoidberg", name:"Zoidberg"}
];